### ISSUE TITLE
Unable to find library

### ISSUE THREAD

**Issue by pravic** [mcgoo/vcpkg-rs#1]
```
t:\>vcpkg list | rg zlib
zlib:x64-windows-static     1.2.11           A compression library
zlib:x86-windows-static     1.2.11           A compression library

t:\>vcpkg_cli probe zlib
Failed:  Could not find library in vcpkg tree Unable to get OUT_DIR

t:\>vcpkg_cli -t x86-windows-static probe zlib
Failed:  this vcpkg build helper can only find libraries built for the MSVC ABI.

t:\>vcpkg_cli -t x86-windows probe zlib
Failed:  this vcpkg build helper can only find libraries built for the MSVC ABI.
```

**Comment by mcgoo** [comment]
(If you're here because of an nmake error in libz-sys on nightly, maybe this is interesting: https://github.com/alexcrichton/libz-sys/pull/18)

If you are looking at the git version of libz-sys, the vcpkg changes have not been published on crates.io yet.

Sorry, the messages are pretty unclear. If you are using the crates.io version of vcpkg_cli, I probably need to make a new release, but here is how it works :
```
PS C:\Users\jim\src\rust\vcpkg-rs\vcpkg_cli> cargo run -- probe zlib -l static
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `C:\Users\jim\src\rust\vcpkg-rs\target\debug\vcpkg_cli.exe probe zlib -l static`
Found library zlib
Include paths:
        C:\Users\jim\src\vcpkg\installed\x64-windows-static\include
Library paths:
        C:\Users\jim\src\vcpkg\installed\x64-windows-static\lib
Runtime Library paths:
Cargo metadata:
        cargo:rustc-link-search=native=C:\Users\jim\src\vcpkg\installed\x64-windows-static\lib
        cargo:rustc-link-lib=static=zlib
Found libs:
        C:\Users\jim\src\vcpkg\installed\x64-windows-static\lib\zlib.lib
PS C:\Users\jim\src\rust\vcpkg-rs\vcpkg_cli> cargo run -- -t i686-pc-windows-msvc probe zlib -l static
    Finished dev [unoptimized + debuginfo] target(s) in 0.0 secs
     Running `C:\Users\jim\src\rust\vcpkg-rs\target\debug\vcpkg_cli.exe -t i686-pc-windows-msvc probe zlib -l static`
Found library zlib
Include paths:
        C:\Users\jim\src\vcpkg\installed\x86-windows-static\include
Library paths:
        C:\Users\jim\src\vcpkg\installed\x86-windows-static\lib
Runtime Library paths:
Cargo metadata:
        cargo:rustc-link-search=native=C:\Users\jim\src\vcpkg\installed\x86-windows-static\lib
        cargo:rustc-link-lib=static=zlib
Found libs:
        C:\Users\jim\src\vcpkg\installed\x86-windows-static\lib\zlib.lib
```

**Comment by pravic** [comment]
I just played with `vcpkg_cli` version from crates.io, yes.

**Comment by mcgoo** [comment]
If you wouldn't mind, can you tell me a little about your configuration? 

Are you actually intending to pick up libraries from Vcpkg at this point or is it accidental? (It finds the tree if you have `VCPKG_ROOT` set or you have run `vcpkg integrate install`.)

What version of the compiler are you using and do you have any RUSTFLAGS set?

Do you have your vcpkg configuration available in a public repository that I could take a look at?

**Comment by pravic** [comment]
Yes, I have VCPKG_ROOT and I do not use vcpkg integration.
I have VS 2015 and 2017 (guess, Rust uses the first one by default).
I have no RUSTFLAGS.

As my vcpkg - it is a default "nightly" vcpkg with the only exception: I use my own curl port, decause the only I need - it is HTTP(s).

**Comment by mcgoo** [comment]
You have to be on nightly Rust, right? Otherwise you shouldn't have seen the nmake breakage...

Is the port called "libcurl" or did you give it a different name?

Are building a mixed C/C++/Rust/something application, or is it just Rust? (If it's just Rust, rust-curl's built in curl is I think configured exactly as yours is, but I believe it will be statically linked so it would probably be easier just to use that.) If you are building a mix of Rust and something else and you want it to all use the same curl then using Vcpkg/vcpkg-rs should be a pretty good solution.

Thanks a lot for the information on this.

**Comment by pravic** [comment]
> Otherwise you shouldn't have seen the nmake breakage...
Why? `cargo +stable build` for curl-sys results the same error as +nightly.

> Is the port called "libcurl"
No, it is the same as [original](https://github.com/Microsoft/vcpkg/tree/master/ports/curl) curl, just stored in different git branch.

> or is it just Rust? 
It is essentially `cargo install-update --all`, it fails on cargo-update command (while building git2, which requires curl).

**Comment by pravic** [comment]
By the way, back to the subject issue:
```
$ cargo install --list | rg vcpkg
vcpkg_cli v0.2.1:
    vcpkg_cli.exe

$ vcpkg list | rg zlib
zlib:x64-windows-static     1.2.11           A compression library
zlib:x86-windows            1.2.11           A compression library
zlib:x86-windows-static     1.2.11           A compression library

$ vcpkg_cli probe zlib
Failed:  Could not find library in vcpkg tree VCPKG_ROOT\installed\x64-windows\lib\zlib.lib

$ vcpkg_cli -t x86-windows-static probe zlib
Failed:  this vcpkg build helper can only find libraries built for the MSVC ABI.

$ vcpkg_cli -t x86-windows probe zlib
Failed:  this vcpkg build helper can only find libraries built for the MSVC ABI.
```

**Comment by mcgoo** [comment]
Oh yeah, sorry - I pushed that release for you but I forgot to mention it.

The `-t` is a Rust target triple. Try:

```
vcpkg_cli probe zlib -l static
vcpkg_cli -t i686-pc-windows-msvc probe zlib -l static
```

and it should find both of those. There is currently no way to make vcpkg_cli call `.lib_names("zlib", "zlib1")` on the Config so even though the libz-sys build script can find the dynamic variant there is no way to verify that from the command line. 

It claims it's working with package names, but it is actually using that as the stem and adding .dll or .lib to find the libraries right now. I'm reworking it to actually work with packages. If you have a moment, I'd be interested to see what you get from 

```
git clone https://github.com/mcgoo/vcpkg-rs
cd vcpkg-rs\vcpkg_cli
git checkout deps
cargo run -- deps curl
```

I get:

```
[...]
=============================
required port ("curl", Port { dlls: ["libcurl.dll"], libs: ["libcurl_imp.lib"], deps: ["zlib", "openssl", "libssh2"] })
required port ("libssh2", Port { dlls: ["libssh2.dll"], libs: ["libssh2.lib"], deps: ["zlib", "openssl"] })
required port ("openssl", Port { dlls: ["libeay32.dll", "ssleay32.dll"], libs: ["libeay32.lib", "ssleay32.lib"], deps: [] })
required port ("zlib", Port { dlls: ["zlib1.dll"], libs: ["zlib.lib"], deps: [] })
Failed:  Could not find library in vcpkg tree C:\Users\jim\src\vcpkg\installed\x64-windows\lib\curl.lib
```

The error at the end is because I'm not done. Hopefully it will parse your installation correctly and you will get something like:
```
required port ("curl", Port { dlls: ["libcurl.dll"], libs: ["libcurl_imp.lib"], deps: [] }) 
```

**Comment by mcgoo** [comment]
Thanks for the walkthrough on what you are trying to do, by the way. I looked up the cargo-update tool - that looks pretty neat.

The original intent of this vcpkg-rs work was to link statically by default, but that turned out not to be possible. Unfortunately, because you are trying to `cargo install` things, and using vcpkg-rs favors dynamic linking, even if the build completes, the resulting binary will not run because it won't be able to find curl.dll. 

It is possible to do static builds if you set `RUSTFLAGS=-Ctarget-feature=+crt-static` and compile with nightly (the initial intent of this work was to make it easier to install diesel_cli). It seems like it would be easier to just disable vcpkg-rs with `NO_VCPKG=1` in your environment. Then, assuming nmake/jobserver issue is now fixed you should be good to go.

This is a disapointing result for me - I was hoping to have it enabled by default, but I think it will have to require a variable to be set to enable it. Sorry again for the breakage.

**Comment by pravic** [comment]
Thanks for detailed explanation.

Yes, now it finds a static zlib (but not zlib1.dll, as you warned above). 

Also it is a bit confusing to have "static", but "dll" instead of "dynamic":
> error: 'dynamic' isn't a valid value for '--linkage <linkage>'
        [values: dll, static]

As for `lib_names` — I think, it is possible to have it in command line tool as well. Since vcpkg_cli is intended for vcpkg feature exploration and testing, it would be nice to have all features covered by command line. Or may be no.

And the last thing: I am worrying about `NO_VCPKG`, would not it be confusing with official `VCPKG_*` variables? May be it is better to use `RUST_VCPKG_*` format?

Anyway, thanks for support.

**Comment by mcgoo** [comment]
`cargo install -f cargo-update` now results in a working binary for me. You should see it pick up vcpkg 0.2.2.

Thanks for the comments about vcpkg_cli - I'll try to remove some of those surprises shortly.

I changed the build help specific environment variables to all have a `VCPKGRS_` prefix to try and keep out of everyone elses' namespace.

Could you let me know if this unbreaks your setup?
