### ISSUE TITLE
Support specifying `VCPKGRS_*` environmental variables from `Config`

### ISSUE THREAD

**Issue by ryankurte** [mcgoo/vcpkg-rs#19]
Hey there,

Would it be possible to configure the `VCPKGRS_*` environmental variables from the `Config` object exposed by the library, with the library setting overridden by the environment?

This would allow us to manage this for different targets in `build.rs`, aiming to simplify the build process for `*-sys` crate consumers.

Somewhat related issue: [rust-embedded#481](https://github.com/rust-embedded/wg/issues/481)

Cheers,

Ryan

**Comment by mcgoo** [comment]
I'm open to the idea, for sure. I assume you are mainly wanting to select which vcpkg triplet to build with? At the moment I think there is no way to do that but I think it would not be a big deal to support it.

**Comment by mcgoo** [comment]
This is now supported from builds.rs as you suggested. It's typically better to use the environment variables because it can be a requirement that all external dependencies come from the same vcpkg installation and use the same triplet.

There is also a new tool `cargo vcpkg` that allows the triplet and required packages to be specified as metadata in Cargo.toml. If required it will create a vcpkg tree from scratch, so `cargo vcpkg build && cargo build` can be enough to get up and running.

**Comment by ryankurte** [comment]
awesome, thanks! i'll try it out next i'm playing with CI tooling
