### ISSUE TITLE
Non-Windows vcpkg-rs

### ISSUE THREAD

**Issue by ras0219-msft** [mcgoo/vcpkg-rs#5]
Now that Vcpkg supports OSX and Linux, would you be interested in PR's enabling support on those platforms?

Currently, the triplets are named `x64-osx` and `x64-linux` and they only build static libs -- there is no `-static` suffix and there are no dynamic variants.

**Comment by mcgoo** [comment]
That would be great!

I just merged a bunch of stuff back to master (automatically including dependent ports finally), so that would be the place to start.

**Comment by ras0219-msft** [comment]
>automatically including dependent ports finally

oooo awesome, I didn't notice that! Looking for it now[1] I see it's quite tricky.

Is there something we could do to make that easier? Specifically, is it reasonable for you to invoke the `vcpkg` executable (and then we could dump out a json file or something) or do you prefer implementing the logic yourself?

[1] https://github.com/mcgoo/vcpkg-rs/commit/329272abc3ae7c02c63e70696d1684e264a502e8#diff-f286f66b95eaad0413cbb6aa3b05f1b1R413

**Comment by mcgoo** [comment]
Late reply sorry. I would be interested in some more structured output from the tool, but I am trying to avoid a dependency on anything else (i.e. `serde`), since in a huge number of builds the use of the `vcpkg` build helper is a no-op. The cost of this is risking getting broken as you add features like features :) So at this point, I'm still not wanting to go there. (Unless the output was something custom and easy to parse, but that removes half of the appeal.)

Is building ports on a windows machine and importing it on macos or linux likely to work? (in the sense of the `vcpkg` binary being able to understand what is there?)

**Comment by ras0219-msft** [comment]
The "database" format is common across all platforms, so yes the binary can definitely understand across multiple platforms. This actually happens regularly today if you use the same vcpkg instance from WSL and Windows. Obviously, OSX can't run Windows executables and vice versa.

We are likely to make some changes to the database format in the future (for example, adding cross-triplet dependencies), but `vcpkg.exe` will be able to read the old format. In the farther future, we may look into switching to something like SQLite for performance if a flat text file becomes too unwieldy, but so far that doesn't look to be an issue.

**Comment by mcgoo** [comment]
Linux and OSX are supported as of 0.2.7 so I'm going to close this. As a side note, I couldn't see any way to determine the link order for Linux libraries (within a single port) since this is encoded in the cmake code, not the status file. If there ends up being a machine readable output type, that would be something useful to add.
